module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/EG8bOdWQm9WKVhw5jG6VTQ',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/v6u3rr.jpg',
    NEWSLETTER_JID: '120363406741941705@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ᴊᴇʀʀʏ-ᴍᴅ',
    OWNER_NAME: 'ᴊᴇʀʀʏ ᴋɪɴɢ',
    OWNER_NUMBER: '639627983648',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ Jᴇʀʀʏ X ᴍᴅ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6wIFEATRSwqmwEky2m',
};
